name: FOSS Scan

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

concurrency: 
  group: fossa-one-at-a-time
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    
    
      - name: Checkout
        uses: actions/checkout@v2

      - name: Java Setup
        uses: actions/setup-java@v2.5.0
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'gradle'

      - name: Fossa Action
        uses: fossa-contrib/fossa-action@v2
        with:
          fossa-api-key: ${{ secrets.FOSSA_API_KEY }}
